<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Maintenance Requests Export</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
            margin: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #ff6200;
            padding-bottom: 10px;
        }

        .header h1 {
            color: #1a2b4c;
            margin: 0;
            font-size: 18px;
        }

        .header p {
            color: #666;
            margin: 5px 0 0;
            font-size: 10px;
        }

        .info-box {
            margin-bottom: 15px;
            padding: 8px;
            background: #f8f9fa;
            border-radius: 5px;
            font-size: 9px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th {
            background: #ff6200;
            color: white;
            padding: 8px 6px;
            text-align: left;
            font-size: 9px;
        }

        td {
            padding: 6px;
            border-bottom: 1px solid #ddd;
            font-size: 9px;
        }

        .status-open {
            color: #1565c0;
            font-weight: bold;
        }

        .status-received {
            color: #1565c0;
            font-weight: bold;
        }

        .status-pending_om {
            color: #856404;
            font-weight: bold;
        }

        .status-in_progress {
            color: #0c5460;
            font-weight: bold;
        }

        .status-pending_vr {
            color: #ff8f00;
            font-weight: bold;
        }

        .status-completed {
            color: #155724;
            font-weight: bold;
        }

        .status-pending_gm {
            color: #0d47a1;
            font-weight: bold;
        }

        .status-closed {
            color: #495057;
            font-weight: bold;
        }

        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 8px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }

        .priority-high {
            background: #ffebee;
        }

        .priority-urgent {
            background: #ffebee;
        }

        .priority-critical {
            background: #ffcdd2;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Maintenance Requests Report</h1>
        <p>{{ config('app.name') }}</p>
    </div>

    <div class="info-box">
        <strong>Export Date:</strong> {{ $exported_at }}<br>
        <strong>Exported By:</strong> {{ $exported_by }}<br>
        <strong>Total Records:</strong> {{ $tickets->total() }}
    </div>

    <table>
        <thead>
            <tr>
                <th>MR Number</th>
                <th>Title</th>
                <th>Category</th>
                <th>Priority</th>
                <th>Status</th>
                <th>Created By</th>
                <th>Created At</th>
                <th>Due Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($tickets as $ticket)
                <td>
                <td>{{ $ticket->ticket_number }}</td>
                <td>{{ Str::limit($ticket->title, 40) }}</td>
                <td>{{ $ticket->category->name ?? 'N/A' }}</td>
                <td class="priority-{{ strtolower($ticket->priority->name ?? '') }}">
                    {{ $ticket->priority->name ?? 'N/A' }}
                </td>
                <td class="status-{{ $ticket->status }}">
                    @php
                        $statusMap = [
                            'open' => 'Open',
                            'received' => 'Received',
                            'pending_om' => 'OM Approval',
                            'in_progress' => 'In Progress',
                            'pending_vr' => 'PR Approval',
                            'completed' => 'Completed',
                            'pending_gm' => 'GM Approval',
                            'ready_for_closure' => 'Ready for Closure',
                            'closed' => 'Closed',
                            'cancelled' => 'Cancelled',
                        ];
                    @endphp
                    {{ $statusMap[$ticket->status] ?? $ticket->status }}
                </td>
                <td>{{ $ticket->user->name ?? 'N/A' }}</td>
                <td>{{ $ticket->created_at->format('d M Y') }}</td>
                <td>{{ $ticket->due_date ? $ticket->due_date->format('d M Y') : '-' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Hotel Maintenance System | {{ date('Y') }}
    </div>
</body>

</html>
